In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("C:\\Users\\Sorabh  Singh\\Desktop\\CSV File\\healthcare-dataset-stroke-data.csv")
#df
df.head(20)

id  gender   age  hypertension  heart_disease ever_married  \
0    9046    Male  67.0             0              1          Yes   
1   51676  Female  61.0             0              0          Yes   
2   31112    Male  80.0             0              1          Yes   
3   60182  Female  49.0             0              0          Yes   
4    1665  Female  79.0             1              0          Yes   
5   56669    Male  81.0             0              0          Yes   
6   53882    Male  74.0             1              1          Yes   
7   10434  Female  69.0             0              0           No   
8   27419  Female  59.0             0              0          Yes   
9   60491  Female  78.0             0              0          Yes   
10  12109  Female  81.0             1              0          Yes   
11  12095  Female  61.0             0              1          Yes   
12  12175  Female  54.0             0              0          Yes   
13   8213    Male  78.0             0              1          Yes   
14   5317  Female  79.0             0              1          Yes   
15  58202  Female  50.0             1              0          Yes   
16  56112    Male  64.0             0              1          Yes   
17  34120    Male  75.0             1              0          Yes   
18  27458  Female  60.0             0              0           No   
19  25226    Male  57.0             0              1           No   

        work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0         Private          Urban             228.69  36.6  formerly smoked   
1   Self-employed          Rural             202.21   NaN     never smoked   
2         Private          Rural             105.92  32.5     never smoked   
3         Private          Urban             171.23  34.4           smokes   
4   Self-employed          Rural             174.12  24.0     never smoked   
5         Private          Urban             186.21  29.0  formerly smoked   
6         Private          Rural              70.09  27.4     never smoked   
7         Private          Urban              94.39  22.8     never smoked   
8         Private          Rural              76.15   NaN          Unknown   
9         Private          Urban              58.57  24.2          Unknown   
10        Private          Rural              80.43  29.7     never smoked   
11       Govt_job          Rural             120.46  36.8           smokes   
12        Private          Urban             104.51  27.3           smokes   
13        Private          Urban             219.84   NaN          Unknown   
14        Private          Urban             214.09  28.2     never smoked   
15  Self-employed          Rural             167.41  30.9     never smoked   
16        Private          Urban             191.61  37.5           smokes   
17        Private          Urban             221.29  25.8           smokes   
18        Private          Urban              89.22  37.8     never smoked   
19       Govt_job          Urban             217.08   NaN          Unknown   

    stroke  
0        1  
1        1  
2        1  
3        1  
4        1  
5        1  
6        1  
7        1  
8        1  
9        1  
10       1  
11       1  
12       1  
13       1  
14       1  
15       1  
16       1  
17       1  
18       1  
19       1

In [3]:
values=22.8
df=df.fillna(value=values)
df

id  gender    age  hypertension  heart_disease ever_married  \
0      9046    Male  67.00             0              1          Yes   
1     51676  Female  61.00             0              0          Yes   
2     31112    Male  80.00             0              1          Yes   
3     60182  Female  49.00             0              0          Yes   
4      1665  Female  79.00             1              0          Yes   
5     56669    Male  81.00             0              0          Yes   
6     53882    Male  74.00             1              1          Yes   
7     10434  Female  69.00             0              0           No   
8     27419  Female  59.00             0              0          Yes   
9     60491  Female  78.00             0              0          Yes   
10    12109  Female  81.00             1              0          Yes   
11    12095  Female  61.00             0              1          Yes   
12    12175  Female  54.00             0              0          Yes   
13     8213    Male  78.00             0              1          Yes   
14     5317  Female  79.00             0              1          Yes   
15    58202  Female  50.00             1              0          Yes   
16    56112    Male  64.00             0              1          Yes   
17    34120    Male  75.00             1              0          Yes   
18    27458  Female  60.00             0              0           No   
19    25226    Male  57.00             0              1           No   
20    70630  Female  71.00             0              0          Yes   
21    13861  Female  52.00             1              0          Yes   
22    68794  Female  79.00             0              0          Yes   
23    64778    Male  82.00             0              1          Yes   
24     4219    Male  71.00             0              0          Yes   
25    70822    Male  80.00             0              0          Yes   
26    38047  Female  65.00             0              0          Yes   
27    61843    Male  58.00             0              0          Yes   
28    54827    Male  69.00             0              1          Yes   
29    69160    Male  59.00             0              0          Yes   
...     ...     ...    ...           ...            ...          ...   
5080  22691  Female  29.00             0              0          Yes   
5081  37680    Male  55.00             0              0          Yes   
5082  24552  Female  44.00             0              0          Yes   
5083  72914  Female  19.00             0              0           No   
5084  29540    Male  67.00             0              0          Yes   
5085  53525  Female  72.00             0              0          Yes   
5086  65411  Female  51.00             0              0          Yes   
5087  26214  Female  63.00             0              0          Yes   
5088  22190  Female  64.00             1              0          Yes   
5089  56714  Female   0.72             0              0           No   
5090   4211    Male  26.00             0              0           No   
5091   6369    Male  59.00             1              0          Yes   
5092  56799    Male  76.00             0              0          Yes   
5093  32235  Female  45.00             1              0          Yes   
5094  28048    Male  13.00             0              0           No   
5095  68598    Male   1.08             0              0           No   
5096  41512    Male  57.00             0              0          Yes   
5097  64520    Male  68.00             0              0          Yes   
5098    579    Male   9.00             0              0           No   
5099   7293    Male  40.00             0              0          Yes   
5100  68398    Male  82.00             1              0          Yes   
5101  36901  Female  45.00             0              0          Yes   
5102  45010  Female  57.00             0              0          Yes   
5103  22127  Female  18.00             0         

In [4]:
#df=pd.get_dummies(df)
df=pd.get_dummies(df,drop_first=True)
df=df.drop(columns=['id'])
print(df)

        age  hypertension  heart_disease  avg_glucose_level   bmi  stroke  \
0     67.00             0              1             228.69  36.6       1   
1     61.00             0              0             202.21  22.8       1   
2     80.00             0              1             105.92  32.5       1   
3     49.00             0              0             171.23  34.4       1   
4     79.00             1              0             174.12  24.0       1   
5     81.00             0              0             186.21  29.0       1   
6     74.00             1              1              70.09  27.4       1   
7     69.00             0              0              94.39  22.8       1   
8     59.00             0              0              76.15  22.8       1   
9     78.00             0              0              58.57  24.2       1   
10    81.00             1              0              80.43  29.7       1   
11    61.00             0              1             120.46  36.8       1   

In [5]:
#df=pd.get_dummies(df)
df=pd.get_dummies(df,drop_first=True)
df

age  hypertension  heart_disease  avg_glucose_level   bmi  stroke  \
0     67.00             0              1             228.69  36.6       1   
1     61.00             0              0             202.21  22.8       1   
2     80.00             0              1             105.92  32.5       1   
3     49.00             0              0             171.23  34.4       1   
4     79.00             1              0             174.12  24.0       1   
5     81.00             0              0             186.21  29.0       1   
6     74.00             1              1              70.09  27.4       1   
7     69.00             0              0              94.39  22.8       1   
8     59.00             0              0              76.15  22.8       1   
9     78.00             0              0              58.57  24.2       1   
10    81.00             1              0              80.43  29.7       1   
11    61.00             0              1             120.46  36.8       1   
12    54.00             0              0             104.51  27.3       1   
13    78.00             0              1             219.84  22.8       1   
14    79.00             0              1             214.09  28.2       1   
15    50.00             1              0             167.41  30.9       1   
16    64.00             0              1             191.61  37.5       1   
17    75.00             1              0             221.29  25.8       1   
18    60.00             0              0              89.22  37.8       1   
19    57.00             0              1             217.08  22.8       1   
20    71.00             0              0             193.94  22.4       1   
21    52.00             1              0             233.29  48.9       1   
22    79.00             0              0             228.70  26.6       1   
23    82.00             0              1             208.30  32.5       1   
24    71.00             0              0             102.87  27.2       1   
25    80.00             0              0             104.12  23.5       1   
26    65.00             0              0             100.98  28.2       1   
27    58.00             0              0             189.84  22.8       1   
28    69.00             0              1             195.23  28.3       1   
29    59.00             0              0             211.78  22.8       1   
...     ...           ...            ...                ...   ...     ...   
5080  29.00             0              0              90.52  28.0       0   
5081  55.00             0              0             108.35  40.8       0   
5082  44.00             0              0              72.03  37.5       0   
5083  19.00             0              0              90.57  24.2       0   
5084  67.00             0              0              97.04  26.9       0   
5085  72.00             0              0              83.89  33.1       0   
5086  51.00             0              0             152.56  21.8       0   
5087  63.00             0              0              75.93  34.7       0   
5088  64.00             1              0              76.89  30.2       0   
5089   0.72             0              0              62.13  16.8       0   
5090  26.00             0              0             100.85  21.0       0   
5091  59.00             1              0              95.05  30.9       0   
5092  76.00             0              0              82.35  38.9       0   
5093  45.00             1              0              95.02  22.8       0   
5094  13.00             0              0              82.38  24.3       0   
5095   1.08             0              0              79.15  17.4       0   
5096  57.00             0              0              76.62  28.2       0   
5097  68.00             0              0              91.68  40.8       0   
5098   9.00             0              0              71.88  17.5       0   
5099  40.00             0              0              83.94  22.8       0   
5100

In [6]:
x=df.iloc[:,:11].values
y=df.iloc[:,11].values
x
y

array([0, 1, 0, ..., 1, 0, 0], dtype=uint8)

In [7]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.2,random_state=0)
train_x

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [8]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(random_state=0)
dtc.fit(train_x,train_y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=0, splitter='best')

In [9]:
pred_y=dtc.predict(test_x)
pred_y

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [10]:
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy_score(test_y,pred_y)

0.8708414872798435

In [13]:
from sklearn.neighbors import KNeighborsClassifier
Knn=KNeighborsClassifier(n_neighbors=3,metric='minkowski')
Knn.fit(train_x,train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [15]:
pred_y=Knn.predict(test_x)
pred_y
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy_score(test_y,pred_y)

0.8189823874755382

In [23]:
from sklearn.svm import SVC
svc=SVC(kernel="linear",random_state=0)
svc.fit(train_x,train_y)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [24]:
pred_y=svc.fit(test_y)
print(pred_y)

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [25]:
from sklearn.metrics import confusion_matrix,accuracy_score
accuracy_score(test_y,pred_y)

0.8923679060665362